# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Digital Dilletante
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  $ dd if=/home/william/brain of=/dev/internets
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://williamfriesen.com" # the base hostname & protocol for your site
github_username:  wfriesen
mastodon_username: tacklingfuel
mastodon_base_url: https://aus.social/
future: true

jekyll_analytics:
  GoogleAnalytics:
    id: UA-103167954-1

# Build settings
markdown: kramdown
exclude: [serve.sh, ./_config.dev.yml]

plugins:
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
  - jekyll-analytics
