# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Last Blog and Testament of William Friesen
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my development-related blog. There are many like it, but this one is mine.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://williamfriesen.com" # the base hostname & protocol for your site
github_username:  wfriesen
future: true

google_analytics: "UA-103167954-1"

# Build settings
markdown: kramdown
exclude: [serve.sh, ./_config.dev.yml]
